[project]
name = "sok-ble"
version = "0.1.0"
description = "SOK BLE battery interface library"
readme = "README.md"
requires-python = ">=3.11"

[tool.ruff]
# Ruff configuration placeholder

[tool.mypy]
# Mypy configuration placeholder
